### PR TITLE
fix download link in readme.md

### PR DESCRIPTION
**Pull request by CircleOnCircles**
fix download links in readme.md

### CODE REVIEW

**Comment by CircleOnCircles** [comment]
I just found out that this link works on the github readme.md, but it might fail on the website.

**Comment by CircleOnCircles** [comment]
I could not check the site since it fails due to dependency.

if it fails, is there anyway to replace str from `](downloads)` -> `](downloads.md)` before deployment.

**Comment by CircleOnCircles** [comment]
[this](https://shopify.github.io/liquid/filters/replace/) might be the way to make the replacement on `README.md`

**Comment by djay** [comment]
Thanks for the pr. 
The problem is to have it working for both the website and the readme which this would break the website.
I think we decided we would remove the readme version and just have the website once we switched it to netlify.

**Comment by djay** [comment]
Where would you add that template tag in order to make it work?

If you can help with jekyll it would be very useful. it's not something I know.

**Comment by CircleOnCircles** [comment]
I'm not sure if the template tag works too, I'm new to Jekyll. I need to identify and inspect the Jekyll build script. and maybe I could insert a pre-build script like `bash sed` or `python str.replace` 

if you think it is doable, you could reopen the pr.

**Pull request closed without merging**
