### PR TITLE
Plot vac_region %

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by djay** [comment]
@modiholodri This is how it looks. It still has a width problem. I don't think it needs decimal here either. Maybe the number of decimals should be an option?
vac_region_2_3

**Comment by modiholodri** [comment]
@djay Looks like a left footnotes issue. It's too big and shifting everything. I'll try to make fixed with tables today, it should look better...

**Comment by djay** [comment]
@modiholodri ok thats easy to fix. I just shortened the footnote.
But I still think for this for this particular plot it doesn't add anything having the decimal. but it would be good to have % maybe?
vac_region_2_3

Also let me know how you think it works within the vac section...

Also need to work out why the colours for the predictions don't match up.

**Comment by modiholodri** [comment]
@djay Yes, the percent should be in there. Concerning the precision I would say that it might not make sense at the moment but it'll make sense later again when the values are closer together. So, to have it all the time is better most of the time and it's also more consistent.

**Pull request merged**
